### ISSUE TITLE
SMM: Ability to create Shard and Shard Map Manager on the same DB

### ISSUE THREAD

**Issue by SilviaDoomra** [Azure/elastic-db-tools#108]
Current design of Shards is that shards and shard map manager cannot live on the same DB. 

However the recommendation for elastic query is to setup elastic query DB with shard and shard map manager on the same DB, which cannot be done with the current implementation.

In addition to that, going down the path, if we want to use the same design for three-part name, we need to have this restriction lifted.

**Comment by jaredmoo** [comment]
Closing as not needed. We don't recommend that the SMM DB is used as a Shard. It's potentially useful for testing/experimentation, but not useful in practice.
