### ISSUE TITLE
can not find the code file:  elastic-db-tools-master\Test\ElasticScale.ShardManagement.UnitTests\ShardKeyInfo.cs

### ISSUE THREAD

**Issue by HyperSkyAdmin** [Azure/elastic-db-tools#119]
Click the "Download Zip" button in the main page to download the code, it can not build success, the error info is:
can not find the code file:  elastic-db-tools-master\Test\ElasticScale.ShardManagement.UnitTests\ShardKeyInfo.cs

**Comment by jaredmoo** [comment]
Oops! Thanks for reporting. Fixing it now.
