### ISSUE TITLE
Build error: The command "powershell Copy-Item D:\elastic-db-tools-master

### ISSUE THREAD

**Issue by HyperSkyAdmin** [Azure/elastic-db-tools#121]
Click "Download Zip" button from main page to download the code, and it can not build success, the error info is:

The command "powershell Copy-Item D:\elastic-db-tools-master\packages D:\elastic-db-tools-master\obj\ElasticScaleStarterKit.csproj\Debug\SamplesGallery\packages -Recurse" exited with code 1.   ElasticScaleStarterKit

Solution:
I edit all *.csproj  files in the elastic-db-tools-master\Samples directory , and delete a line of code:
`<Import Project="..\SamplesGallery.targets" />`

Then it can build success.

All the *.csproj  files is:
elastic-db-tools-master\Samples\ElasticDapper.csproj
elastic-db-tools-master\Samples\EntityFrameworkMultiTenant.csproj
elastic-db-tools-master\Samples\ElasticScaleStarterKit.csproj
elastic-db-tools-master\Samples\EntityFrameworkCodeFirst.csproj
elastic-db-tools-master\Samples\ShardSqlCmd.csproj

But if I download the 1.2.0 code from github "Release" menu:  
https://github.com/Azure/elastic-db-tools/releases
the *.csproj also contains code `<Import Project="..\SamplesGallery.targets" />`  ,
but it can build success, do not need to delete the code `<Import Project="..\SamplesGallery.targets" />`.

**Comment by jaredmoo** [comment]
Thanks for the report! Since this issue only affects samples and not the product code, and since you found a workaround, I classified this issue as low priority for now. Please keep reporting any issues you find! :)

**Comment by jaredmoo** [comment]
Fixed by new build system.
