### ISSUE TITLE
Support Active  Directory Authentication for GSM and LSM connections

### ISSUE THREAD

**Issue by apurvans** [Azure/elastic-db-tools#123]
.NET 4.6 added support for active directory authentication. Update client library to support AD authentication (ActiveDirectoryIntegrated and ActiveDirectoryPassword) if running with .net 4.6

**Comment by abatishchev** [comment]
Any update on this, please?

**Comment by jaredmoo** [comment]
This was done, it should work as of v1.3.2. Cheers
