### ISSUE TITLE
UnauthorizedAccessException: Access to the registry key 'Global' is denied.

### ISSUE THREAD

**Issue by Schenz** [Azure/elastic-db-tools#129]
Stack Trace:

Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str):126
 Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity):0
 Microsoft.Win32.RegistryKey.GetValue(String name):10
 System.Diagnostics.PerformanceMonitor.GetData(String item):24
 System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item):61
 System.Diagnostics.PerformanceCounterLib.get_CategoryTable():39
 System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category):8
 System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName):122
 System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName):0
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.PerfCounterInstance..ctor(String shardMapName):13
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.CacheShardMap..ctor(IStoreShardMap ssm):74
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.CacheRoot.AddOrUpdate(IStoreShardMap ssm):0
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.CacheStore.AddOrUpdateShardMap(IStoreShardMap shardMap):12
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.FindShardMapByNameGlobalOperation.DoGlobalUpdateCachePost(IStoreResults result):21
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperationGlobal.<Do>b__0():84
 Microsoft.Azure.SqlDatabase.ElasticScale.TransientFaultHandling+RetryPolicy.ExecuteAction[TResult](Func`1 func):115
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperationGlobal.Do():23
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ShardMapManager.LookupShardMapByNameInStore(String operationName, String shardMapName):15
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ShardMapManager.LookupShardMapByName(String operationName, String shardMapName, Boolean lookInCacheFirst):27
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ShardMapManager.LookupAndConvertShardMapHelper[TShardMap](String operationName, String shardMapName, Func`3 converter, Boolean throwOnFailure):0
 Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ShardMapManager.TryGetListShardMap[TKey](String shardMapName, ListShardMap`1& shardMap):54

**Comment by jaredmoo** [comment]
Thanks for the bug report! We will investigate.

**Comment by Schenz** [comment]
it works fine locally, but when I deploy to an Azure AppService (Website) is where I saw the exception

**Comment by apurvans** [comment]
Hi Brandon,

I have published a PreRelease version (1.3.1-rc-001) of client library which fixes this issue. I have verified correct error handling in a sample Azure AppService. Can you please try this version and let us know if it works for you.
prerelease version: https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/1.3.1-rc-001

Thanks,
Apurva

**Comment by apurvans** [comment]
Published new version 1.3.1 on nuget with fix for this issue. https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/
