### ISSUE TITLE
ShardManagement.psm1 can't download Client package from NuGet

### ISSUE THREAD

**Issue by abatishchev** [Azure/elastic-db-tools#139]
Hi,
I downloaded the latest scripts from [TechNet](https://gallery.technet.microsoft.com/scriptcenter/Azure-SQL-DB-Elastic-731883db/view/Discussions#content) and ran this command:

    >PS C:\Users\alexbat\Downloads> .\GetShards.ps1 -UserName x -Password y -ShardMapManagerServerName z -ShardMapManagerDatabaseName a -ShardMapName b

But recieved an error:
```
C:\Users\alexbat\Downloads\ShardManagement\Microsoft.Azure.SqlDatabase.ElasticScale.Client.dll was not found.
Would you like to download it from NuGet?
[Y] Yes  [N] No  [?] Help (default is "N"): y
Unable to find package 'Microsoft.Azure.SqlDatabase.ElasticScale.Client'.
copy : Cannot find path 'C:\Users\alexbat\Downloads\ShardManagement\Microsoft.Azure.SqlDatabase.ElasticScale.Client\lib
\net45\Microsoft.Azure.SqlDatabase.ElasticScale.Client.dll' because it does not exist.
At C:\Users\alexbat\Downloads\ShardManagement\ShardManagement.psm1:57 char:21
+             $null = copy "$ScriptDir\$edclPackage\lib\net45\$edclFile" $edclPath
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\alexba...cale.Client.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

Searching for `$edclPackage` or `$edclFile` [yielded no results](https://www.google.com/search?q=%24edclFile&ie=utf-8&oe=utf-8) other than this repo.

**Comment by jaredmoo** [comment]
Ensure that `nuget.org` exists in your package sources with location `https://www.nuget.org/api/v2/`, which you can see by running `Get-PackageSource` in powershell. You can update this by modifying your [global nuget.config](https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior) and restarting powershell.

**Comment by abatishchev** [comment]
Paradoxically it helped: I had only nuget.org v3 api, once added v2 as well it has worked. Thanks!

**Comment by BalwantPatel** [comment]
I don't know where to change in the config file.

  <packageSources>

    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />

  </packageSources>

**Comment by jaredmoo** [comment]
This is in my config: `<add key="https://www.nuget.org/api/v2/" value="https://www.nuget.org/api/v2/" />`

**Comment by beloblotskiy** [comment]
It's easy to fix by adding
```
Unregister-PackageSource -Name "nuget.org"
Register-PackageSource -Name "nuget.org" -Location "https://www.nuget.org/api/v2/" -ProviderName nuget
```
in the Common\AzureShardManagement.psm1
before $package = Find-Package -Name $edclPackage -ProviderName nuget -Source nuget.org
