### ISSUE TITLE
New release of Elastic DB tools

### ISSUE THREAD

**Issue by ramondeklein** [Azure/elastic-db-tools#140]
I am desperate for a new version of the Elastic Database tools. The latest version (on NuGet) is Elastic Scale client v1.3.2. We cannot use this version, because of some async issues (resolved with pull request #136). For that reason, we use a custom build of the Elastic tools.

We also use the (closed-source) split/merge tool and use ` Microsoft.Azure.SqlDatabase.ElasticScale.SplitMerge.Client.dll` to access it from our application. This assembly uses strong-names, so I cannot redirect it to use my custom build.

Could you please release a v1.3.3 build of `Microsoft.Azure.SqlDatabase.ElasticScale.Client.dll` that has the proper signing to work with the split/merge tool?

**Comment by jaredmoo** [comment]
Yes, I can do an official release this week. Sorry to keep you waiting, I didn't realize how urgent this was for you.

**Comment by jaredmoo** [comment]
Just wanted to follow up on this - I've made the official 1.3.3 build, currently working on getting it uploaded to nuget.org.

**Comment by ramondeklein** [comment]
Thanks very much.

**Comment by jaredmoo** [comment]
1.3.3 is out: https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/

**Comment by jaredmoo** [comment]
And thanks again for your code contribution!
