### ISSUE TITLE
Connection Leaking v1.3.3

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/elastic-db-tools#149]
Hi Team,

_Solution background:_
MVC WebApp using Ninject DI for the Repository pattern (InRequestScope used).

 public SomeDbContext(ShardMap shardMap, T shardingKey, string connectionStr)
            : base(CreateShardConnection(shardMap, shardingKey, connectionStr),
 **true** /*contextOwnsConnection */)

I have noticed an issue with connection leaking, I have noticed that a large number of connections are trying to "create procedure __ShardManagement.spValidateShardMappingLocal".
these connections appear to remain after the repositories associated with the called controller have been disposed. The connections to the ShardMangerDB function as expected and are working fine.
I have turn connection pooling off for the interim.

this problem "_seems_" to have become more prevalent after upgrading from 1.3.2 to 1.3.3.  or perhaps as  I suspect I am just doing more incorrect things more often :) standard user error some might say.

**_DIAG SQL:_**
SELECT ec.session_id, last_read, last_write, text, client_net_address, program_name, host_process_id, login_name, es.status
FROM sys.dm_exec_connections  ec
JOIN sys.dm_exec_sessions es
  ON ec.session_id = es.session_id
CROSS APPLY sys.dm_exec_sql_text(ec.most_recent_sql_handle) AS dest
where es.status = 'sleeping'

Appreciate your time, Thank you.

**Comment by ConX-Ryan** [comment]
further investigation leads me to **OpenConnection** function on line 535 of file ShardMap.cs

in this function a new connection is made by the call
` IUserStoreConnection conn = this.Manager.StoreConnectionFactory.GetUserConnection(connectionStringFinal);`

which is opened in the using statement
`using (ConditionalDisposable<IUserStoreConnection> cd = new ConditionalDisposable<IUserStoreConnection>(conn))`

inside the using statement is the line 
`cd.DoNotDispose = true;`

which is important to be set true otherwise no valid connection is returned but when is this connection disposed?

**Comment by jaredmoo** [comment]
OpenConnection (if successful) returns an open connection to the caller. When this connection is passed to an EF context, that context is responsible for disposing the connection.

`create procedure __ShardManagement.spValidateShardMappingLocal` should only be called when creating a shard (see `ShardMap.CreateShard` which calls into `AddShardOperation` or upgrading the SMM version (`UpgradeStoreLocalOperation`)

**Comment by ConX-Ryan** [comment]
I have a sneaking suspicion I am stuck in "upgrade mode" which would explain the create procs and also i have a number of  System.Data.Entity.Core.EntityException thrown. maybe commit b11c107 did not address this as expected?

I will try and roll back and note results

**Comment by ConX-Ryan** [comment]
Sorry to waste your time, it seems i was distracted by the update process and the leak was entirely some place else.

**Comment by jaredmoo** [comment]
Glad you figured it out!
