### ISSUE TITLE
Marking a point mapping offline killing active connections to affected shard

### ISSUE THREAD

**Issue by bjbxx** [Azure/elastic-db-tools#150]
Marking a point mapping offline in order to delete that mapping kills all active connections to the affected shard.  However, the documentation seems to indicate this is only needed for range mappings: 

> In addition, when a range is first taken offline, all connections to the affected shard are automatically killed in order to prevent inconsistent or incomplete results for queries directed against ranges being changed.

When looking through the source, that seems to be the intended behavior for both list and range shard maps.  Is that correct, and if so, is there a way to bypass this behavior for a list shard map?

**Comment by jaredmoo** [comment]
Yes this is intended behavior for both list and range mappings. This behavior is intended to ensure safety - marking the mapping offline kills connections and blocks future connections, which ensures you don't accidentally have a connection using that key during or after marking the mapping offline. 

However I can understand in some circumstances this may be painful for you and you might want to implement your own safety mechanism that doesn't require killing connections. There is no way to bypass this currently, but I'd be happy to discuss a design to optionally allow this and/or review a pull request :)

**Comment by bjbxx** [comment]
Appreciate the response and that makes sense.

I suspect that we'd want overload `MarkMappingOffline` with an enum that would allow us to skip this operation (similar to `OpenConnectionForKeyAsync` with its `ConnectionOptions`)? 

Thanks!

**Comment by jaredmoo** [comment]
Yep that's exactly what I was thinking 👍
