### ISSUE TITLE
Inconsistent Licensing

### ISSUE THREAD

**Issue by paulirwin** [Azure/elastic-db-tools#160]
This repository appears to be the main source repository for the [Microsoft.Azure.SqlDatabase.ElasticScale.Client NuGet package](https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/). The code here has a LICENSE file that is the MIT license. However, the NuGet package links to [this license](http://elasticscale.blob.core.windows.net/sdk/SQL%20DB%20Elastic%20Scale%20EULA.htm) as its License Info URL, which is not MIT and prohibits production use in non-Azure environments.

Please make the NuGet package for this library MIT licensed as well, without any restriction for production use in non-Azure environments. This library should work just fine on SQL Server and it would be good to have the option of a hybrid approach.

**Comment by jaredmoo** [comment]
Thanks for reporting this issue!
