### ISSUE TITLE
Debug stepping in/through the biggest pile of spaghetti (aka elastic-db-tools)

### ISSUE THREAD

**Issue by LastTribunal** [Azure/elastic-db-tools#162]
Has anyone tried to step into this code?
There are at least a thousand steps per every execution.  
This "library" needs to be rewritten from scratch.  
I can't imagine having this in production.  
And his is the only "library" that leverages Azure Elastic SQL?!
What am embarrassment...

Perhaps MS no longer gives a rats about SQL and is putting all their eggs into Cosmos..

**Comment by jaredmoo** [comment]
I'm sorry you had difficulty debugging, can you clarify what you mean by 'steps per execution'?

**Comment by LastTribunal** [comment]
Thanks Jared, and apologies for my belligerence.  If use you do ShardMap.OpenConnectionForKey from a client, and then  Debug.StepInto (F11), you will see the debugger jump to code statements.  You will see very many of these jumps, I stopped counting after several hundred.  My point is, that there seems to be too much complexity in this code and it will cause slow performance in production.

**Comment by jaredmoo** [comment]
If you find any specific performance issue, please let us know. Thanks :)
