### ISSUE TITLE
How far away is a .NET Core version?

### ISSUE THREAD

**Issue by erick-thompson** [Azure/elastic-db-tools#164]
I am trying to build a .NET Core application using the elastic client. How far away is an official build targeting netstandard2? In the meantime, is the .NET Core branch in a usable state?

**Comment by jaredmoo** [comment]
No ETA for an official signed & published build but the NetCore branch should be usable and if you try it out I would love to hear any positive or negative feedback you have.

I'm closing this issue as a duplicate, the main discussion is at https://github.com/Azure/elastic-db-tools/issues/118 .
