### ISSUE TITLE
.NET Standard 2.0 update

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/elastic-db-tools#168]
Great framework here, any plans to give it some love and update to .NET Standard?

**Comment by jaredmoo** [comment]
Thanks! Already done, you can download the source and try it out: https://github.com/Azure/elastic-db-tools/tree/NetCore

**Comment by ConX-Ryan** [comment]
Cheers Team!!! I must have missed it on NuGet or something

**Comment by jaredmoo** [comment]
It is not uploaded to nuget yet. I am still slowly working on that :)

**Comment by paulirwin** [comment]
@jaredmoo Thanks for doing this port to .NET Standard! Any updates? 😉

**Comment by jaredmoo** [comment]
Thanks for your patience. I have built a nuget package and just uploaded it to https://github.com/Azure/elastic-db-tools/releases/tag/v2.0.0-preview1 . Please try this out and let me know if it works well or if you ran into any issues.

**Comment by paulirwin** [comment]
@jaredmoo Awesome, any way you can get this preview published to NuGet as a prerelease?

**Comment by paulirwin** [comment]
Btw, I just successfully tested this library against both .NET Framework 4.7.1 and .NET Core 2.0.

**Comment by jaredmoo** [comment]
Thanks for the feedback and patience. It is now published on nuget.
https://github.com/Azure/elastic-db-tools/releases/tag/v2.0.0-preview2
https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.0.0-preview2
