### ISSUE TITLE
SqlCredential: Support Secure Credential passing for Sql operations

### ISSUE THREAD

**Issue by stuartpa** [Azure/elastic-db-tools#170]
The SqlConnection object supports receiving a Sql Authentication password as a SecureString wrapped in the SqlCredential object, enabling a secret to be held in managed memory as an encrypted object, which is a recommended security practice as part of a defense in depth strategy.  See ASP.Net blog titled: Safer passwords with SqlCredential

However, the ElasticScale.Client API that leverages partial Sql Connection strings to interact with both the Shard Map Manager and individual Shards, prevents a SecureString from being used with the SqlConnection object, causing any application using the ElasticScale.Client API that has to support the Sql Auth surface area, to un-encrypt SecureStrings in managed memory, before passing the secret to the ElasticScale library via the ConnectionString (rather than a secure SqlCredential, containing a SecureString).

The recommendation here is to support the SqlCredential type, as a non-breaking change, in all places where an unencrypted connection string is asked for in the API.  This could be done by either adding function overloads to all relevant public APIs (which are already heavily overloaded), or adding an optional parameter to the existing public APIs.  Is there feedback on which of these two paths would be the best fit?

i.e. As an optional parameter, the change would look like this:

From:

public static ShardMapManager CreateSqlShardMapManager(
            string connectionString,
            ShardMapManagerCreateMode createMode)
        {

public static ShardMapManager CreateSqlShardMapManager(
            string connectionString,
            ShardMapManagerCreateMode createMode,
            SqlCredential secureCredential = null)
        {

**Comment by jaredmoo** [comment]
👍 
Please be aware that optional parameters are against .net framework design guidelines. So we would have to add overloads instead.
