### ISSUE TITLE
Official package with net core support

### ISSUE THREAD

**Issue by rotsin** [Azure/elastic-db-tools#175]
Hi guys, great work on the package!

I have a question related to the roadmap and availability for the net core official support version. Are there any plans to continue development for the net core version and if so, are there any milestones available or public roadmap for them?

**Comment by tlentine** [comment]
Do you happen to have a publicly available target for when the stable package might be available? This is one of the blockers we're facing for migrating to .NET Core ourselves, so anything you could share would greatly help us with our own planning efforts.
Thanks for the great work!

**Comment by jaredmoo** [comment]
There are no significant code changes remaining, I just have to rebuild the package. However I wasn't able to immediately do this because we have a new internal process for signing the package that is taking some time to work through. Thanks for your comments :) I love hearing this passionate feedback!

**Comment by jaredmoo** [comment]
It's finally done: https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client

Thanks for your patience :)

**Comment by rotsin** [comment]
> It's finally done: https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client
> 
> Thanks for your patience :)

Hey Jared,

We've installed it a couple of weeks ago, it seems to work fine, thank you so much for your work!

**Comment by tlentine** [comment]
> > It's finally done: https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client
> > Thanks for your patience :)
> 
> Hey Jared,
> 
> We've installed it a couple of weeks ago, it seems to work fine, thank you so much for your work!

Agreed, it's working great!
