### ISSUE TITLE
Major pain to restore packages and build samples

### ISSUE THREAD

**Issue by PapaStahl** [Azure/elastic-db-tools#176]
Using Visual Studio 2017 on Win 10 professional 64-bit.

I was trying to run through both the EF Code First and EF Multi Tenant sample projects, but I don't get any further than these build errors:

The command "powershell Add-Type -Assembly System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::CreateFromDirectory('obj\x86\Debug\\SamplesGallery', 'bin\Debug\\EntityFrameworkMultiTenantSamplesGallery.zip', [System.IO.Compression.CompressionLevel]::Optimal, $false)" exited with code 1.	EntityFrameworkMultiTenant	C:\Source\GitHub\elastic-db-tools\Samples\SamplesGallery.targets	49

**Comment by jaredmoo** [comment]
Understood, these projects were originally created in order to automate building of sample projects to visual studio gallery. When we switched build system and open-sourced all the code, we never updated the sample projects. Thanks for the feedback.

**Comment by PapaStahl** [comment]
@jaredmoo Thank you so much for resolving this so quickly! I just pulled the latest commit and everything builds flawlessly!
