### ISSUE TITLE
Method needed: string ShardMap.GetConnectionStringForKey(TKey)

### ISSUE THREAD

**Issue by wiatr22** [Azure/elastic-db-tools#181]
I would like to create SqlConnection for specified key myself, (OpenConnectionForKey(...) is not what I need). I need the ElasticScale should return exact connection string for key. Can you help me in this matter?

I know I could use 'GetMappingForKey(TKey key)' but  as far as I analyzed the source code this method does not use internal cache. I am going to consume the method heavily so it MUST use internal cache to prevent database agains unneeded ovelload. Could you please help me?

**Comment by jaredmoo** [comment]
I think this is solved by #178. I just need to re-review and merge it.

**Comment by wiatr22** [comment]
Change #178 looks fine for me untill 'lookupOptions' parameter is exposed to a public method, not only internal. So I am looking forward a new merge and library version.

**Comment by jaredmoo** [comment]
Fixed in #178, released v2.1.0. Cheers!
