### ISSUE TITLE
Rename Shard Mapped Database

### ISSUE THREAD

**Issue by aherrick** [Azure/elastic-db-tools#182]
If I'm using the Catalog/Tenant structure with ShardMap my DB that gets generated is the sname name as registered.

I'm using the following to get the ID of my Tenant.

```
var md5 = MD5.Create();
			var tenantHashBytes = md5.ComputeHash(tenantNameBytes);

			// Convert to integer for use as the key in the catalog
			return BitConverter.ToInt32(tenantHashBytes, 0);
```

I then use the following to open the connection for the key:

`Sharding.ShardMap.OpenConnectionForKey`

My question is simple, after the DB/Tenant has already been associated in the database, how do I rename the Tenant and associated __ShardManagement tables.

**Comment by jaredmoo** [comment]
The tenant name is the sharding key, right? Can you add a new key which maps to the same shard (so it exists with both old and new names), then migrate your app to use the new key, then remove the old key?
