### ISSUE TITLE
Add support for MSI

### ISSUE THREAD

**Issue by thomasvdb** [Azure/elastic-db-tools#184]
We're currently looking at enabling Azure Active Directory authentication for our Azure Elastic databases.

One of the issues I'm investigating is how Entity Framework migrations will work with Azure AD authentication enabled.

At the moment our release pipeline is calling a batch script which executes the following piece of code:

```
var connBuilder = new SqlConnectionStringBuilder(smmconnstr);
connBuilder.DataSource = smmserver;
connBuilder.InitialCatalog = smmdatabase;

ShardMapManagerFactory.TryGetSqlShardMapManager(connBuilder.ConnectionString, ShardMapManagerLoadPolicy.Lazy, out var ShardMapManager);
ShardMapManager.TryGetListShardMap<Guid>("...", out var ShardMap))

IEnumerable<Shard> shards = ShardMap.GetShards();
foreach (Shard shard in shards)
{
    var connStrBldr = new SqlConnectionStringBuilder(connectionString);
    connStrBldr.DataSource = shard.Location.DataSource;
    connStrBldr.InitialCatalog = shard.Location.Database;

    var dbMigrator = new DbMigrator(
            new MigrationsConfiguration()
            {
                AutomaticMigrationsEnabled = false,
                AutomaticMigrationDataLossAllowed = false,
                TargetDatabase = new DbConnectionInfo(connStrBldr.ConnectionString, "System.Data.SqlClient")
            });
    IEnumerable<string> localMigrations = dbMigrator.GetLocalMigrations();
    if (localMigrations.Any())
    {
        dbMigrator.Update();
    }
}
```

Because we're now using a connection string with a SQL user configured I was looking at using the following [sample](https://github.com/Azure-Samples/app-service-msi-entityframework-dotnet) to be able to configure it with AD authentication.

However when running the above code again, I get the following error `The required property 'Password' must be set in the connection string.` on the line `ShardMapManagerFactory.TryGetSqlShardMapManager(connBuilder.ConnectionString, ShardMapManagerLoadPolicy.Lazy, out var ShardMapManager);`

When adding the Password property in the connection string with a dummy value I get the following erorr: `'Cannot use 'Authentication=Active Directory Interactive' with 'PWD' connection string keywords.'`

Is this use-case supported? Am I doing something wrong?

**Comment by jaredmoo** [comment]
Which version are you using? This should be already fixed, see https://github.com/Azure/elastic-db-tools/pull/133

**Comment by thomasvdb** [comment]
I'm using version 2.1.0.0 of the Microsoft.Azure.SqlDatabase.ElasticScale.Client NuGet package

**Comment by jaredmoo** [comment]
Ah, I see the problem. We are only skipping the password check if auth is AD *Integrated*, not AD *Interactive*.

https://github.com/Azure/elastic-db-tools/blob/accessToken/Src/ElasticScale.Client/ShardManagement/SqlStore/SqlShardMapManagerCredentials.cs#L162

**Comment by jaredmoo** [comment]
Can you please try the code from the attached PR?

**Comment by thomasvdb** [comment]
Just to be sure, I should create a build myself with the new code?
I'll try this as soon as possible.

**Comment by jaredmoo** [comment]
That's right. Thanks!

**Comment by thomasvdb** [comment]
I'm getting a different issue now but I think that's not related to this library but to the Microsoft.Azure.Services.AppAuthentication NuGet package from the [sample](https://github.com/Azure-Samples/app-service-msi-entityframework-dotnet).

`Failed to instantiate an authentication provider with type 'Microsoft.Azure.Services.AppAuthentication.SqlAppAuthenticationProvider, Microsoft.Azure.Services.AppAuthentication' for 'ActiveDirectoryInteractive'.`

For me this issue can be closed, thanks!

**Comment by jaredmoo** [comment]
Thank you for the confirmation!
