### ISSUE TITLE
Nuget package isn't signed

### ISSUE THREAD

**Issue by sebbe33** [Azure/elastic-db-tools#192]
Starting with Microsoft.Azure.SqlDatabase.ElasticScale.Client. 2.0.0, it seems that the .dll's in the Nuget package are no longer being signed. This becomes a problem when trying to sign our own .dll's which have dependencies on the ElasticScale.Client library. 

Could you please add back the signing task to your build pipeline and make sure the next version of the Nuget package is signed?

Thanks,
// Seb

**Comment by jaredmoo** [comment]
https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.2.0

**Comment by sebbe33** [comment]
Thanks for the quick response in getting this out
