### ISSUE TITLE
Assembly is not signed with a strong name

### ISSUE THREAD

**Issue by sebbe33** [Azure/elastic-db-tools#194]
Related to [#140](https://github.com/Azure/elastic-db-tools/issues/192). In version 2.2.0, the .dlls are now digitally signed again, but they don't seem to be signed with a strong name. I'm getting the following errors when trying to build a project that is signed with a strong name and has a dependency on ElasticScale.Client.

```
Error CS8002 Referenced assembly 'Microsoft.Azure.SqlDatabase.ElasticScale.Client, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

Is there any chance you could sign the Microsoft.Azure.SqlDatabase.ElasticScale.Client assembly with a strong name?

Thanks,
// Seb

**Comment by jaredmoo** [comment]
Correct, I will fix this but it will most likely need to be a different strong name key than v1.x due to major changes in our build infrastructure since then. Will this be a problem?

**Comment by sebbe33** [comment]
No, that shouldn't be a problem. Thanks

**Comment by jaredmoo** [comment]
Release v2.3.0
