### ISSUE TITLE
Command timeout exception on ASP.NET application for long running queries.

### ISSUE THREAD

**Issue by wiatr22** [Azure/elastic-db-tools#198]
I have found strange error that appear only for long running queries. The error is repeatable on ASP.Net application (both web forms, and MVC) but does not happen in Windows Form application. The code is:

            var shardLocations = new ShardLocation[] { new ShardLocation(@"(local)", "MyDb")};
            using (var conn = new MultiShardConnection(shardLocations, "Integrated Security=True"))
            {
                using (MultiShardCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = "WAITFOR DELAY '00:00:35.100'; SELECT GETDATE();";
                    cmd.CommandTimeout = 60;

                    Stopwatch sw = Stopwatch.StartNew();
                    int rows = 0;
                    using (var reader = cmd.ExecuteReader())
                    {
                        while(reader.Read())
                            rows++;
                    }
                    sw.Stop();

                    lbDuration.Text = $"{DateTimeOffset.Now}. RowCount: {rows}. Duration: {sw.Elapsed}";
                }
            }

The code results in the exception: System.TimeoutException: Command timeout of 60 elapsed. "SELECT GETDATE()" should last miliseconds so no reason for this exception.

However, if the query lasts shorter time, waitfor is less then 30 seconds ("WAITFOR DELAY '00:00:25.100'; SELECT GETDATE();"), the code works fine with no errors. Is there any explanation for this strange behawior?

Visual Studio 2017, SqlServer 2017, Microsoft.Azure.SqlDatabase.ElasticScale.Client version="2.3.0"

**Comment by wiatr22** [comment]
That's my fault. I have mistaken the MultiShardCommand.CommantTimeout property and MultiShardCommand.CommantTimeoutPerShard property. My code with

cmd.CommandTimeoutPerShard = 60;

works OK

**Comment by jaredmoo** [comment]
Awesome, thanks for sharing the solution! :)
