### ISSUE TITLE
2.4.0 nuget

### ISSUE THREAD

**Issue by AHelper** [Azure/elastic-db-tools#202]
Hi,

I've been working on moving all of our SQL connections to connect using MSI access tokens while hosted in app services in Azure.  The last part was to migrate our sharding logic.  Since ShardMapManagerFactory changes to allow passing in a SqlConnectionInfo are in master and not a nuget, I tested against a local build. So far, so good :+1:.  However, I've shelved those changes for now.

What's the release schedule look like for getting these recent changes into a published nuget?

Thanks!

**Comment by lukerogers** [comment]
We are very interested in this too. Any chance to publish this, even as a preview version?

**Comment by Nico-VanHaaster** [comment]
When will this be released. We are having to rely on a local version of this repo!

**Comment by danofiveo** [comment]
> When will this be released. We are having to rely on a local version of this repo!

Same here. This is especially problematic when using the [PowerShell](https://github.com/Azure/elastic-db-tools/blob/master/Samples/PowerShell/ShardManagement/ShardManagement.psm1) module since it downloads from NuGet.

**Comment by hayesst** [comment]
Any updates on when the changes for Access Tokens will be released?
Thanks for any info.

**Comment by thomasvdb** [comment]
Interested in this as well. Any update on this?

**Comment by RobLSDev** [comment]
I've pinged the "nuget owner", and hoping we hear back on this issue soon.  Access Token support would be great to have so we can get rid of managing a bunch of secrets.

**Comment by thomasvdb** [comment]
@RobLSDev Did the same via support and got this response: https://github.com/Azure/elastic-db-tools/issues/210#issuecomment-792515506

**Comment by stuartpa** [comment]
2.4.0 preview 2 released with .Net 6.0 and M.D.S support

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.0-preview2

If there are no issues, I'll release it as 2.4.0

**Comment by SaifAqqad** [comment]
@stuartpa Now that .NET 8 is released and there are [compatibility issues with .NET 8 and System.Data.SqlClient](https://github.com/dotnet/runtime/issues/86969), I think it's time to release 2.4.0 (non preview) on nuget.

**Comment by stuartpa** [comment]
2.4.0 released to nuget.org:

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.0

Release notes:

https://github.com/Azure/elastic-db-tools/releases/tag/v2.4.0

Let me know if you hit any issues
