### ISSUE TITLE
Update to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by michaelnero** [Azure/elastic-db-tools#203]
Do you have any plans to migrate to Microsoft.Data.SqlClient? I'd be happy to help with the migration by opening a PR if you have a preference for how you'd want it implemented.

I have a local version where the netstandard20 target references the Microsoft.Data.SqlClient package instead of System.Data.SqlClient and with compiler directives that use the Microsoft.Data.SqlClient namespace for NETSTANDARD2_0. It works, but it required a lot of changes across quite a few files, and I'm not sure that's the direction you want to go anyway.

Let me know what your thoughts are and if I can help.

**Comment by markdj** [comment]
Would also like to know if there are plans for this. We need to be able to support sql always encrypted and I think this will be required to get it working. Unless there's another way to make that work with this project I'd be happy to hear it.

**Comment by krish-gh** [comment]
Any update on this?

**Comment by FeistyMango** [comment]
Would also love to see support for Microsft.Data.SqlClient as EF Core 3 now has converted to using this instead. I'm currently having to pay a double hand shake cost when invoking:
`Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMap<TKey>.OpenConnectionForKey(TKey key, string connectionString)`

I am then taking the connection string within the returned `System.Data.SqlClient.SqlConnection` object, and then constructing a `Microsoft.Data.SqlClient.ConnectionString` object. This also includes some fun string manipulation to inject the credentials into the connection string as well. However, the major issue here is the wasteful first call to open the connection just to obtain connection string.

**Comment by FeistyMango** [comment]
Seems like the work has been completed to support this and the PR has been open for a year now? Could this be merged and have an official nuget release deployed?

https://github.com/Azure/elastic-db-tools/pull/205

**Comment by vd94** [comment]
Any update on this? Is this going to be deployed?

**Comment by mcox-ng** [comment]
@vd94 we gave up waiting and forked the repository along with the PR #205 and built our own package. Problem solved

**Comment by mwillebrands** [comment]
Any update on this?

**Comment by hanssubadvies** [comment]
We want to update to Microsoft.Data.SqlClient version 5.0.0. Anyone updating this code? Any alternatives other than; do not use sharding?

**Comment by stuartpa** [comment]
I'll bump to M.D.S 5.1.1 and release a 2.4.0-preview3 (preview2 is already M.D.S, but at 3.0.0)

**Comment by stuartpa** [comment]
PR to bump M.D.S  to 5.1.1: #235

**Comment by stuartpa** [comment]
2.4.0+ released.
