### ISSUE TITLE
Access token support for shard connection

### ISSUE THREAD

**Issue by vd94** [Azure/elastic-db-tools#211]
Hi Team,

I want to confirm is there any support provided for setting AccessToken in database connection in case of Azure AD login, for both ShardManager as well as for each Shard?
I can see some accesstokenfactory parameter for SqlConnectionInfo, but could not found anything to pass that from caller code.

**Comment by wilsjd** [comment]
The latest code isn't packaged in a release. I just forked it and packaged it privately to be able to use the AccessToken and SqlConnectionInfo.

**Comment by stuartpa** [comment]
2.4.0 preview 2 released with .Net 6.0 and M.D.S support

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.0-preview2

If there are no issues, I'll release it as 2.4.0.

**Comment by stuartpa** [comment]
2.4.0 released to nuget.org:

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.0

Release notes:

https://github.com/Azure/elastic-db-tools/releases/tag/v2.4.0

Let me know if you hit any issues

**Comment by vd94** [comment]
Finally this has been upgraded and there seems active work after a long time on this repo and package releases. Thank you @stuartpa.
Closing this issue.
