### ISSUE TITLE
ShardManagementException missing Inner Exception for StoreException

### ISSUE THREAD

**Issue by snavjot** [Azure/elastic-db-tools#214]
ShardManagementException returned by [GetStoreExceptionGlobal ](https://github.com/Azure/elastic-db-tools/blob/f6a3543293610181fccdde479273d7b6b43a9e21/Src/ElasticScale.Client/ShardManagement/Utils/ExceptionUtils.cs#L91-L103) does not contain Inner Exception. 
This can be easily fixed by calling the correct constructor. 
Currently [GetStoreExceptionGlobal ](https://github.com/Azure/elastic-db-tools/blob/f6a3543293610181fccdde479273d7b6b43a9e21/Src/ElasticScale.Client/ShardManagement/Utils/ExceptionUtils.cs#L91) is calling [Constructor](https://github.com/Azure/elastic-db-tools/blob/f6a3543293610181fccdde479273d7b6b43a9e21/Src/ElasticScale.Client/ShardManagement/ShardMapManager/ShardManagementException.cs#L284-L285) which does not take inner exception. In place if the [constructor](https://github.com/Azure/elastic-db-tools/blob/f6a3543293610181fccdde479273d7b6b43a9e21/Src/ElasticScale.Client/ShardManagement/ShardMapManager/ShardManagementException.cs#L315-L316) which takes inner exception is invoked. It will fix the bug.

**Comment by snavjot** [comment]
This pull request #215 fixes the issue.

**Comment by stuartpa** [comment]
#215 Merged
