### ISSUE TITLE
Does ShardMap support Microsoft.Data.SqlClient package?

### ISSUE THREAD

**Issue by jsquire** [Azure/elastic-db-tools#225]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#33247](https://github.com/Azure/azure-sdk-for-net/issues/33247).

### Library name and version

Microsoft.Data.SqlClient

### Query/Question

I have an .net core 6.0 entityframework application and want to connect to SQL Database through Azure Active Directory from the application. The code to connect to SQL Database through Azure Active Directory uses Microsoft.Data.SqlClient as the package. We also have usage of ShardMap in the same DbContext where we are connecting to the database. The ShardMap does not support Microsoft.Data.SqlClient and needs System.Data.SqlClient as the package. Does, ShardMap support Microsoft.Data.SqlClient package ?

Below is piece of code from the DbContext where I am getting the error:

```csharp
SqlConnection conn = null; //uses Microsoft.Data.SqlClient as the package
  try{   
   var shardMap = GetShardMapManager(Constants.Settings.ShardMapName, configuration);
   var connStringBuilder = new SqlConnectionStringBuilder
   {
      UserID = userId,
      Password = password,
      ApplicationName = "ABC"
   };
        
  conn = shardMap.OpenConnectionForKey(shardingKey, connStringBuilder.ConnectionString, ConnectionOptions.Validate);\
         
   //Gives error at the above line: "Cannot convert source type 'System.Data.SqlClient.SqlConnection' to target type 'Microsoft.Data.SqlClient.SqlConnection'"
   /* If the above SqlConnection uses System.Data.SqlClient.SqlConnection as the package, the error does not come up. But, in that case, we cannot use Authentication in the GetDatabaseConnection method.
   */
   }
  catch (Exception e) 
  {
  ......
  }
 
 private static ShardMap GetShardMapManager(string shardMapName, IConfiguration configuration)
  {
      var dbConnectionString = GetDatabaseConnectionString(configuration);
      var shardMapManager = ShardMapManagerFactory.GetSqlShardMapManager(dbConnectionString, ShardMapManagerLoadPolicy.Lazy);
      var shardMap = shardMapManager.GetListShardMap<int>(shardMapName);
      return shardMap;
  }
```

//The method below needs Microsoft.Data.SqlClient to use Authentication=Active Directory Service Principal;

```csharp
public static string GetDatabaseConnection(IConfiguration config)
  {
   return
                  $"Server=tcp:{config["SERVERNAME"]},1433; Authentication=Active Directory Service Principal; " +
                  $"Encrypt=True; Database={config[DATABASENAME]}; User Id = {clientId}; Password = {password} ";
        
   var connection = new SqlConnection(ConnectionString);
      connection.Open();
  }
```

### Environment

EF Core 6.0
IDE: JetBrains Rider 2022.3.1

**Comment by jholovacs** [comment]
I believe this is tracked in #220.
See also https://github.com/MicrosoftDocs/azure-docs/issues/102976#issuecomment-1361378829

**Comment by davejitsu** [comment]
I tried the preview2, and it's working so far with no issues. When will we have the production ready version? Thanks!

**Comment by stuartpa** [comment]
Great news to hear preview2 is working for you with no issues.  I haven't heard of anyone having any issues (I can see the preview has has been downloaded a few 1000s times from nuget.org).  If things continue with no issues, I'll release 2.4 next week.

**Comment by stuartpa** [comment]
2.4.0 released to nuget.org:

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.0

Release notes:

https://github.com/Azure/elastic-db-tools/releases/tag/v2.4.0

Let me know if you hit any issues
