### ISSUE TITLE
Missing support for 'Active Directory Default' authentication

### ISSUE THREAD

**Issue by billpieper** [Azure/elastic-db-tools#246]
Currently, this library is missing support for Active Directory Default authentication

https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#setting-microsoft-entra-authentication

**Comment by stuartpa** [comment]
Thanks for the issue and PR.  I'll merge this and release it on Monday.

**Comment by billpieper** [comment]
Any chance this can be released soon?

**Comment by stuartpa** [comment]
Yes, sorry I'm late on this, will get a release done this weekend.

**Comment by billpieper** [comment]
^^ Would love to see this published to unblock us so we don't have to roll our own version...

**Comment by stuartpa** [comment]
Sorry, I got diverted onto something else.  I will get this done tomorrow.

**Comment by stuartpa** [comment]
2.4.1 released:

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.1
