### ISSUE TITLE
ElasticScaleStarterKit: Timeout errors on create database.

### ISSUE THREAD

**Issue by jaredmoo** [Azure/elastic-db-tools#42]
We received feedback that some users are hitting timeout errors on create database. We should consider increasing the CommandTimeout.

**Comment by stuartpa** [comment]
I've seen this recently (testing AAD support).  Moved time out to 3 mins (from 1 min), which seems to avoid the issue.  #237

**Comment by stuartpa** [comment]
2.4.0 released to nuget.org:

https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/2.4.0

Release notes:

https://github.com/Azure/elastic-db-tools/releases/tag/v2.4.0

Let me know if you hit any issues
