### ISSUE TITLE
Make SqlBulkCopy with DDR easy

### ISSUE THREAD

**Issue by SilviaDoomra** [Azure/elastic-db-tools#89]
Using SqlBulkCopy with the DDR API has a lot of friction. As a DDR user, I want to feed data into the SqlBulkCopy object and have it automatically fanout to the correct shard, but this doesn’t work nicely because SqlBulkCopy only accepts one SqlConnection. It's possible to write a fairly simple sharded bulkcopy object that bucketizes rows based on shard and then does individual SqlBulkCopy to each shard (being careful to redo the bucketization if the shard map changes before/during the bulkcopy), but what happens if bulkcopy of rows to shard 1 succeeds and bulkcopy to shard 2 fails? Now our sharded bulkcopy is in a weird partially-committed state. This will require some design thought and discussion.

**Comment by jaredmoo** [comment]
Requires design. No current plan to address it.
