### ISSUE TITLE
SMM: version check APIs

### ISSUE THREAD

**Issue by SilviaDoomra** [Azure/elastic-db-tools#91]
We have APIs for upgrading the GSM and LSMs of a ShardMapManager, but we don't have APIs for determining what is the current version of a GSM or LSM. 
 
The API must allow a user to determine what SMM store version is supported by this version of the library for a chosen store type. Note that the store version is a property of the underlying storage, which currently it always SQL server but it is abstracted such that other storage would be possible. Also it would be preferable if the user should be able to determine the supported store version without needing to first create or get a ShardMapManager.
 
We would like to discuss possible designs first before choosing one.
 
Here is one approach, which is to change ShardMapManagerFactory from being a static factory to be an abstract factory which is subclassed for different storage types. It’s not a breaking change as long as we continue to support the existing public static factory methods.
 
Something like this:
 
public abstract class ShardMapManagerFactory
{
                public Version SupportedGlobalVersion  { get; }
                public Version SupportedLocalVersion  { get; }
                public event Action<RetryingEventArgs> Retrying { get; }
 
                public abstract ShardMapManager Create();
                public abstract ShardMapManager Get();
                public abstract ShardMapManager Create();
                public abstract ShardMapManager Get();
 
                // Refactoring of existing method
                public static ShardMapManager CreateSqlShardMapManager(string connectionString)
                {
                                return new SqlShardMapManagerFactory(connectionString).Create();
}
}
 
public class SqlShardMapManagerFactory
{
                public SqlShardMapManagerFactory(string connectionString)
                {
                }
}

**Comment by jaredmoo** [comment]
No apparent demand for this feature.
