### ISSUE TITLE
Make EDCL compatible with ADO.Net Connection Resiliency 

### ISSUE THREAD

**Issue by SilviaDoomra** [Azure/elastic-db-tools#93]
With the current implementation of EDCL, we break all the connections to shard to avoid any new connections to be sent to it. According to the current implementation of the ADO.Net, it will retry the connection if it sees a broken connection. EDCL explicitly makes that connection tagged in such a way that no reties happen. 

We need to make updates to EDCL to ensure it works with ADO.Net connection resiliency.

**Comment by jaredmoo** [comment]
This is by design. We have retries at a higher level so that we can do connection validation.
